export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const FETCH_U_REQUEST = "FETCH_U_REQUEST";
export const FETCH_U_SUCCESS = "FETCH_U_SUCCESS";

export const FETCH_REGISTRATION_ERROR =
  "FETCH_REGISTRATION_ERROR";
export const FETCH_AUTHORIZATION_ERROR =
  "FETCH_AUTHORIZATION_ERROR";
export const SET_USER_DATA = "SET_USER_DATA";

export const SET_CURRENT_CAFE = "SET_CURRENT_CAFE";
export const SET_CAFE_LIST = "SET_CAFE_LIST";
export const CLEAR_CURRENT_CAFE = "CLEAR_CURRENT_CAFE";
export const CLEAR_CAFE_LIST = "CLEAR_CAFE_LIST";
